### ISSUE TITLE
Cannot update the Atmega 2560 through USB

### ISSUE THREAD

**Issue by noradtux** [PrusaOwners/mk3-32u2-firmware#1]
After putting this firmware onto the 32u2 of my mk3 avrdude fails to push firmware to the 2560. Otherwise the printer works over USB.

This is the output:
/usr/bin/avrdude -v -q -p m2560 -c stk500v2 -P /dev/ttyACM0 -D -U flash:w:/tmp/Firmware.ino.hex:i 

avrdude: Version 6.3, compiled on Jul 10 2020 at 20:46:49
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/etc/avrdude.conf"
         User configuration file is "/root/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/ttyACM0
         Using Programmer              : stk500v2
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
         AVR Part                      : ATmega2560
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    10     8    0 no       4096    8      0  9000  9000 0x00 0x00
           flash         65    10   256    0 yes    262144  256   1024  4500  4500 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : STK500V2
         Description     : Atmel STK500 Version 2.x firmware
         Programmer Model: Unknown
avrdude: stk500v2_ReceiveMessage(): timeout

**Comment by Arksine** [comment]
Could be a couple of things:
- The flash didn't take.  However, this should have been obvious during the flashing procedure
- Something is wrong with the bootloader on the 2560

I would suggest checking the output of `dmesg` to make sure that the device is correctly enumerating as a Prusa MK3.  Should look something like this:
```
[    4.513286] systemd[1]: Set hostname to <klipper-mk3>.
[    4.612560] usb 1-1.4: New USB device found, idVendor=2c99, idProduct=0002, bcdDevice= 1.00
[    4.619238] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.622558] usb 1-1.4: Product: Original Prusa i3 MK3
[    4.625706] usb 1-1.4: Manufacturer: Prusa Research (prusa3d.com)
[    4.628714] usb 1-1.4: SerialNumber: <your serial here>
[    7.805336] cdc_acm 1-1.4:1.0: ttyACM0: USB ACM device
```

Also you can verify that /dev/ttyACM0 is the correct device:
```
pi@klipper-mk3:~/moonraker $ ls -lah /dev/serial/by-id
total 0
drwxr-xr-x 2 root root 60 Mar 17 06:40 .
drwxr-xr-x 4 root root 80 Mar 17 06:40 ..
lrwxrwxrwx 1 root root 13 Mar 17 06:40 usb-Prusa_Research__prusa3d.com__Original_Prusa_i3_MK3_<your_serial>-if00 -> ../../ttyACM0
```

**Comment by noradtux** [comment]
my kernel output looks ok, also the alias for ttyACM0 is there. I will try to program the 2560 through its ISP and see if that helps.

**Comment by Arksine** [comment]
Let me ask, does Klipper's `make flash` work?  I took a closer look at your avrdude command it appears you are trying to flash an .ino file.  That doesn't seem right to me, you need to flash either a hex or a binary. 

Edit: on second thought it does appear to be a hex file.  Still, I would check to see if make flash works.

**Comment by noradtux** [comment]
Okay, I just tried again. Now it works. Difference is that the printer was disconnected, so I guess unpowering the 32u2 did the trick.
