### ISSUE TITLE
Does this work with the MK3S?

### ISSUE THREAD

**Issue by AndreasReitberger** [PrusaOwners/mk3-32u2-firmware#2]
Just made the update on my MK3S and was confused if this is actually also for the MK3S?
Or is there a new firmware needed?

Thank you,
Andreas

**Comment by Arksine** [comment]
Yes, it will work on the MK3S, as it uses the same Einsy Rambo that the MK3 did.

**Comment by AndreasReitberger** [comment]
Perfect, thanks for the clarification.
